version: '3.7'

services:
  notebook:
    build: ./
    ports:
      - 4321:8888
    volumes:
      - .:/home/jovyan/
    depends_on:
      - postgis
  postgis:
    image: mdillon/postgis
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=carto
    volumes:
      - ./pgdata:/var/lib/postgresql/data

